server:
  port: 7777

spring:
  datasourse:
    url: jdbc:h2:mem:tastdb

  h2:
    console:
      enable: true

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml